# Generated by Django 4.2.3 on 2023-12-07 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('due_date', models.DateField(default=datetime.date(9999, 12, 31))),
                ('tag', models.CharField(default='OPEN', max_length=100)),
            ],
        ),
    ]
